This project is guided by https://machinelearningmastery.com/how-to-develop-convolutional-neural-network-models-for-time-series-forecasting/

# Univariate CNN Models

Univariate data: comprise of a single series of observations with temporal ordering.

For CNN to work on this kind of data, we must transform it multiple example from which the model can learn.

Example:

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

can be transformed to 

X -> Y

[10, 20, 30] -> [40]

[20, 30, 40] -> [50]

[30, 40, 50] -> [60]

...


## Implementing split sequence 

In [9]:
import numpy as np

In [16]:
def split_sequence(input_series, step_size):
    """
    Split time series data to multiple input arrays
    Input:
        input_series: list
            A list of time series univariate data
        step_size: int
            step to split up data
    Return:
        X: numpy array
            Input data
        Y: numpy array
            Output data
    """
    current_index = 0
    X = []
    Y = []
    while current_index + step_size < len(input_series):
        current_x = input_series[current_index: current_index + step_size]
        current_y = input_series[current_index + step_size]
        current_index += 1
        X.append(current_x)
        Y.append(current_y)
    return np.asarray(X), np.asarray(Y)

## CNN model

In [140]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers import Input
from keras.layers.merge import concatenate
from keras.models import Model

In [31]:
def training_model(n_steps, n_features):
    """
    Define CNN model
    Input:
        n_steps: int
            step size from split series procedure
        n_features: int 
    """
    model = Sequential()
    model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, n_features)))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Flatten())
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')
    
    return model

## Start training

In [32]:
input_series = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
n_steps = 3
n_features = 1

In [33]:
X, y = split_sequence(input_series, n_steps)
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [34]:
model = training_model(n_steps, n_features)

In [35]:
model.fit(X, y, epochs=1000, verbose=1)

Epoch 1/1000
7/7 [==============================] - 1s 129ms/step - loss: 5227.8594
Epoch 2/1000
7/7 [==============================] - 0s 517us/step - loss: 5087.1079
Epoch 3/1000
7/7 [==============================] - 0s 473us/step - loss: 4947.5776
Epoch 4/1000
7/7 [==============================] - 0s 268us/step - loss: 4808.8936
Epoch 5/1000
7/7 [==============================] - 0s 215us/step - loss: 4671.3506
Epoch 6/1000
7/7 [==============================] - 0s 209us/step - loss: 4536.5835
Epoch 7/1000
7/7 [==============================] - 0s 208us/step - loss: 4405.5522
Epoch 8/1000
7/7 [==============================] - 0s 242us/step - loss: 4275.8286
Epoch 9/1000
7/7 [==============================] - 0s 323us/step - loss: 4147.0640
Epoch 10/1000
7/7 [==============================] - 0s 297us/step - loss: 4019.2417
Epoch 11/1000
7/7 [==============================] - 0s 215us/step - loss: 3892.6340
Epoch 12/1000
7/7 [==============================] - 0s 225us/step - loss:

Epoch 99/1000
7/7 [==============================] - 0s 260us/step - loss: 20.3118
Epoch 100/1000
7/7 [==============================] - 0s 273us/step - loss: 20.2040
Epoch 101/1000
7/7 [==============================] - 0s 188us/step - loss: 20.0697
Epoch 102/1000
7/7 [==============================] - 0s 136us/step - loss: 19.9171
Epoch 103/1000
7/7 [==============================] - 0s 130us/step - loss: 19.7544
Epoch 104/1000
7/7 [==============================] - 0s 127us/step - loss: 19.5889
Epoch 105/1000
7/7 [==============================] - 0s 189us/step - loss: 19.4275
Epoch 106/1000
7/7 [==============================] - 0s 164us/step - loss: 19.2748
Epoch 107/1000
7/7 [==============================] - 0s 178us/step - loss: 19.1366
Epoch 108/1000
7/7 [==============================] - 0s 216us/step - loss: 19.0151
Epoch 109/1000
7/7 [==============================] - 0s 870us/step - loss: 18.9118
Epoch 110/1000
7/7 [==============================] - 0s 173us/step - loss: 1

Epoch 197/1000
7/7 [==============================] - 0s 180us/step - loss: 17.3953
Epoch 198/1000
7/7 [==============================] - 0s 242us/step - loss: 17.3778
Epoch 199/1000
7/7 [==============================] - 0s 437us/step - loss: 17.3603
Epoch 200/1000
7/7 [==============================] - 0s 390us/step - loss: 17.3427
Epoch 201/1000
7/7 [==============================] - 0s 369us/step - loss: 17.3250
Epoch 202/1000
7/7 [==============================] - 0s 419us/step - loss: 17.3073
Epoch 203/1000
7/7 [==============================] - 0s 231us/step - loss: 17.2895
Epoch 204/1000
7/7 [==============================] - 0s 283us/step - loss: 17.2717
Epoch 205/1000
7/7 [==============================] - 0s 160us/step - loss: 17.2538
Epoch 206/1000
7/7 [==============================] - 0s 232us/step - loss: 17.2359
Epoch 207/1000
7/7 [==============================] - 0s 221us/step - loss: 17.2179
Epoch 208/1000
7/7 [==============================] - 0s 197us/step - loss: 

Epoch 295/1000
7/7 [==============================] - 0s 233us/step - loss: 15.1415
Epoch 296/1000
7/7 [==============================] - 0s 228us/step - loss: 15.1168
Epoch 297/1000
7/7 [==============================] - 0s 240us/step - loss: 15.0911
Epoch 298/1000
7/7 [==============================] - 0s 181us/step - loss: 15.0648
Epoch 299/1000
7/7 [==============================] - 0s 202us/step - loss: 15.0377
Epoch 300/1000
7/7 [==============================] - 0s 188us/step - loss: 15.0100
Epoch 301/1000
7/7 [==============================] - 0s 331us/step - loss: 14.9839
Epoch 302/1000
7/7 [==============================] - 0s 173us/step - loss: 14.9593
Epoch 303/1000
7/7 [==============================] - 0s 227us/step - loss: 14.9326
Epoch 304/1000
7/7 [==============================] - 0s 204us/step - loss: 14.9039
Epoch 305/1000
7/7 [==============================] - 0s 234us/step - loss: 14.8781
Epoch 306/1000
7/7 [==============================] - 0s 169us/step - loss: 

Epoch 393/1000
7/7 [==============================] - 0s 273us/step - loss: 11.9969
Epoch 394/1000
7/7 [==============================] - 0s 181us/step - loss: 11.9637
Epoch 395/1000
7/7 [==============================] - 0s 191us/step - loss: 11.9307
Epoch 396/1000
7/7 [==============================] - 0s 230us/step - loss: 11.8970
Epoch 397/1000
7/7 [==============================] - 0s 863us/step - loss: 11.8621
Epoch 398/1000
7/7 [==============================] - 0s 248us/step - loss: 11.8282
Epoch 399/1000
7/7 [==============================] - 0s 206us/step - loss: 11.7933
Epoch 400/1000
7/7 [==============================] - 0s 228us/step - loss: 11.7600
Epoch 401/1000
7/7 [==============================] - 0s 200us/step - loss: 11.7238
Epoch 402/1000
7/7 [==============================] - 0s 202us/step - loss: 11.6903
Epoch 403/1000
7/7 [==============================] - 0s 222us/step - loss: 11.6559
Epoch 404/1000
7/7 [==============================] - 0s 204us/step - loss: 

Epoch 492/1000
7/7 [==============================] - 0s 174us/step - loss: 8.4425
Epoch 493/1000
7/7 [==============================] - 0s 143us/step - loss: 8.4110
Epoch 494/1000
7/7 [==============================] - 0s 206us/step - loss: 8.3805
Epoch 495/1000
7/7 [==============================] - 0s 167us/step - loss: 8.3473
Epoch 496/1000
7/7 [==============================] - 0s 237us/step - loss: 8.3117
Epoch 497/1000
7/7 [==============================] - 0s 194us/step - loss: 8.2738
Epoch 498/1000
7/7 [==============================] - 0s 337us/step - loss: 8.2337
Epoch 499/1000
7/7 [==============================] - 0s 221us/step - loss: 8.1925
Epoch 500/1000
7/7 [==============================] - 0s 219us/step - loss: 8.1669
Epoch 501/1000
7/7 [==============================] - 0s 192us/step - loss: 8.1365
Epoch 502/1000
7/7 [==============================] - 0s 173us/step - loss: 8.0994
Epoch 503/1000
7/7 [==============================] - 0s 215us/step - loss: 8.0566
Epoc

Epoch 591/1000
7/7 [==============================] - 0s 199us/step - loss: 5.0752
Epoch 592/1000
7/7 [==============================] - 0s 172us/step - loss: 5.0472
Epoch 593/1000
7/7 [==============================] - 0s 190us/step - loss: 5.0176
Epoch 594/1000
7/7 [==============================] - 0s 203us/step - loss: 4.9860
Epoch 595/1000
7/7 [==============================] - 0s 176us/step - loss: 4.9526
Epoch 596/1000
7/7 [==============================] - 0s 217us/step - loss: 4.9194
Epoch 597/1000
7/7 [==============================] - 0s 141us/step - loss: 4.8902
Epoch 598/1000
7/7 [==============================] - 0s 238us/step - loss: 4.8587
Epoch 599/1000
7/7 [==============================] - 0s 269us/step - loss: 4.8280
Epoch 600/1000
7/7 [==============================] - 0s 155us/step - loss: 4.7957
Epoch 601/1000
7/7 [==============================] - 0s 224us/step - loss: 4.7695
Epoch 602/1000
7/7 [==============================] - 0s 160us/step - loss: 4.7388
Epoc

Epoch 690/1000
7/7 [==============================] - 0s 426us/step - loss: 2.4229
Epoch 691/1000
7/7 [==============================] - 0s 393us/step - loss: 2.3999
Epoch 692/1000
7/7 [==============================] - 0s 232us/step - loss: 2.3793
Epoch 693/1000
7/7 [==============================] - 0s 222us/step - loss: 2.3586
Epoch 694/1000
7/7 [==============================] - 0s 219us/step - loss: 2.3379
Epoch 695/1000
7/7 [==============================] - 0s 277us/step - loss: 2.3161
Epoch 696/1000
7/7 [==============================] - 0s 1ms/step - loss: 2.2976
Epoch 697/1000
7/7 [==============================] - 0s 258us/step - loss: 2.2774
Epoch 698/1000
7/7 [==============================] - 0s 267us/step - loss: 2.2537
Epoch 699/1000
7/7 [==============================] - 0s 231us/step - loss: 2.2371
Epoch 700/1000
7/7 [==============================] - 0s 215us/step - loss: 2.2186
Epoch 701/1000
7/7 [==============================] - 0s 199us/step - loss: 2.1986
Epoch 

Epoch 789/1000
7/7 [==============================] - 0s 361us/step - loss: 0.8627
Epoch 790/1000
7/7 [==============================] - 0s 219us/step - loss: 0.8492
Epoch 791/1000
7/7 [==============================] - 0s 200us/step - loss: 0.8403
Epoch 792/1000
7/7 [==============================] - 0s 184us/step - loss: 0.8320
Epoch 793/1000
7/7 [==============================] - 0s 175us/step - loss: 0.8224
Epoch 794/1000
7/7 [==============================] - 0s 196us/step - loss: 0.8117
Epoch 795/1000
7/7 [==============================] - 0s 207us/step - loss: 0.8004
Epoch 796/1000
7/7 [==============================] - 0s 272us/step - loss: 0.7887
Epoch 797/1000
7/7 [==============================] - 0s 213us/step - loss: 0.7822
Epoch 798/1000
7/7 [==============================] - 0s 214us/step - loss: 0.7743
Epoch 799/1000
7/7 [==============================] - 0s 177us/step - loss: 0.7642
Epoch 800/1000
7/7 [==============================] - 0s 160us/step - loss: 0.7525
Epoc

Epoch 888/1000
7/7 [==============================] - 0s 255us/step - loss: 0.2203
Epoch 889/1000
7/7 [==============================] - 0s 393us/step - loss: 0.2165
Epoch 890/1000
7/7 [==============================] - 0s 238us/step - loss: 0.2137
Epoch 891/1000
7/7 [==============================] - 0s 209us/step - loss: 0.2106
Epoch 892/1000
7/7 [==============================] - 0s 208us/step - loss: 0.2072
Epoch 893/1000
7/7 [==============================] - 0s 235us/step - loss: 0.2036
Epoch 894/1000
7/7 [==============================] - 0s 251us/step - loss: 0.1998
Epoch 895/1000
7/7 [==============================] - 0s 222us/step - loss: 0.1971
Epoch 896/1000
7/7 [==============================] - 0s 207us/step - loss: 0.1937
Epoch 897/1000
7/7 [==============================] - 0s 190us/step - loss: 0.1910
Epoch 898/1000
7/7 [==============================] - 0s 198us/step - loss: 0.1883
Epoch 899/1000
7/7 [==============================] - 0s 327us/step - loss: 0.1853
Epoc

Epoch 987/1000
7/7 [==============================] - 0s 186us/step - loss: 0.0410
Epoch 988/1000
7/7 [==============================] - 0s 290us/step - loss: 0.0403
Epoch 989/1000
7/7 [==============================] - 0s 175us/step - loss: 0.0395
Epoch 990/1000
7/7 [==============================] - 0s 252us/step - loss: 0.0389
Epoch 991/1000
7/7 [==============================] - 0s 214us/step - loss: 0.0382
Epoch 992/1000
7/7 [==============================] - 0s 168us/step - loss: 0.0374
Epoch 993/1000
7/7 [==============================] - 0s 198us/step - loss: 0.0368
Epoch 994/1000
7/7 [==============================] - 0s 315us/step - loss: 0.0360
Epoch 995/1000
7/7 [==============================] - 0s 193us/step - loss: 0.0354
Epoch 996/1000
7/7 [==============================] - 0s 189us/step - loss: 0.0348
Epoch 997/1000
7/7 [==============================] - 0s 174us/step - loss: 0.0341
Epoch 998/1000
7/7 [==============================] - 0s 247us/step - loss: 0.0335
Epoc

### Test model

In [41]:
x_input = np.asarray([90,100,110])
x_input = x_input.reshape((1, x_input.shape[0], n_features))

In [42]:
yhat = model.predict(x_input, verbose=0)

In [43]:
yhat

array([[122.46071]], dtype=float32)

#### Close enough

# Multivariate CNN model

Multivariate data: There are more than one observation for each time step

Two main model:

    - Multiple Input Series
    
    - Multiple Parallel Series

## Multiple Input Series

Problem: multiple input time series and output put is a time serie that depends on those.

In [121]:
def split_sequences_multiple_input(input_series, n_steps):
    X = []
    y = []
    current_pos = 0
    while current_pos + n_steps < len(input_series) + 1:
        current_x = [i[:-1].tolist() for i in input_series[current_pos:current_pos + n_steps]]
        current_y = input_series[current_pos + n_steps - 1][-1]
        X.append(current_x)
        y.append(current_y)
        current_pos += 1
    return np.asarray(X), np.asarray(y)

## Generate data

In [122]:
from numpy import array 
from numpy import hstack

In [123]:
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

In [124]:
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

print(out_seq.shape)

(9, 1)


In [125]:
# Stack column
dataset = hstack((in_seq1, in_seq2, out_seq))

In [128]:
X, y = split_sequences_multiple_input(dataset, 3)

In [129]:
def multi_input_series_model(n_steps, n_features):
    model = Sequential()
    model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, n_features)))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Flatten())
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')
    return model

In [130]:
n_features = X.shape[2]
n_steps = 3

In [131]:
model = multi_input_series_model(n_steps, n_features)
model.fit(X, y, epochs=1000, verbose=0)

## Predict

In [133]:
x_input = array([[80, 85], [90, 95], [100, 105]])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[206.15164]]


## Multi-headed CNN model

Each input series can be handle by seperate CNN and the output of each submodels can be combined before a predictioin is made for the output

In [147]:
def multi_headed_CNN(n_steps, n_features):
    visible1 = Input(shape=(n_steps, n_features))
    cnn1 = Conv1D(filters=64, kernel_size=2, activation='relu')(visible1)
    cnn1 = MaxPooling1D(pool_size=2)(cnn1)
    cnn1 = Flatten()(cnn1)
    
    visible2 = Input(shape=(n_steps, n_features))
    cnn2 = Conv1D(filters=64, kernel_size=2, activation='relu')(visible2)
    cnn2 = MaxPooling1D(pool_size=2)(cnn2)
    cnn2 = Flatten()(cnn2) 
    
    merge = concatenate([cnn1, cnn2])
    dense = Dense(50, activation='relu')(merge)
    output = Dense(1)(dense)
    
    model = Model(inputs=[visible1, visible2], outputs=output)
    model.compile(optimizer='adam', loss='mse')
    return model

In [146]:
# Seperate input data
n_features = 1
X1 = X[:, :, 0].reshape(X.shape[0], X.shape[1], n_features)
X2 = X[:, :, 1].reshape(X.shape[0], X.shape[1], n_features)

In [148]:
model = multi_headed_CNN(n_steps, n_features)

In [150]:
model.fit([X1, X2], y, epochs=1000, verbose=0)

### Predict

In [151]:
x_input = array([[80, 85], [90, 95], [100, 105]])
x1 = x_input[:, 0].reshape((1, n_steps, n_features))
x2 = x_input[:, 1].reshape((1, n_steps, n_features))
yhat = model.predict([x1, x2], verbose=0)
print(yhat)

[[207.5158]]


## Multiple Parallel Series

Predict multiple n next number

In [152]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix, :]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [160]:
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps = 3
# convert into input/output
X, y = split_sequences(dataset, n_steps)
n_features = X.shape[2]

In [161]:
def parallel_model(n_steps, n_features):
    model = Sequential()
    model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, n_features)))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Flatten())
    model.add(Dense(50, activation='relu'))
    model.add(Dense(n_features))
    model.compile(optimizer='adam', loss='mse')
    
    return model

In [162]:
model = parallel_model(n_steps, n_features)
model.fit(X, y, epochs=3000, verbose=0)

### Predict

In [163]:
x_input = array([[70,75,145], [80,85,165], [90,95,185]])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[100.86671 106.38293 207.5009 ]]


We can use seperate CNN model to predict output

In [168]:
# define model
def multiple_output_model(n_steps, n_features):
    visible = Input(shape=(n_steps, n_features))
    cnn = Conv1D(filters=64, kernel_size=2, activation='relu')(visible)
    cnn = MaxPooling1D(pool_size=2)(cnn)
    cnn = Flatten()(cnn)
    cnn = Dense(50, activation='relu')(cnn)
    
    output1 = Dense(1)(cnn)
    # define output 2
    output2 = Dense(1)(cnn)
    # define output 3
    output3 = Dense(1)(cnn)
    
    # tie together
    model = Model(inputs=visible, outputs=[output1, output2, output3])
    model.compile(optimizer='adam', loss='mse')
    
    return model

In [167]:
# separate output
y1 = y[:, 0].reshape((y.shape[0], 1))
y2 = y[:, 1].reshape((y.shape[0], 1))
y3 = y[:, 2].reshape((y.shape[0], 1))

In [169]:
model = multiple_output_model(n_steps, n_features)
model.fit(X, [y1, y2, y3], epochs=2000, verbose=0)

### Predict

In [170]:
x_input = array([[70,75,145], [80,85,165], [90,95,185]])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[array([[100.50763]], dtype=float32), array([[105.92335]], dtype=float32), array([[206.66423]], dtype=float32)]


# Multi-Step CNN models

## Data preparation

You can just compare this to the first one for deeper understanding

In [171]:
def split_sequence(sequence, n_steps_in, n_steps_out):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps_in
		out_end_ix = end_ix + n_steps_out
		# check if we are beyond the sequence
		if out_end_ix > len(sequence):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [172]:
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# split into samples
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[10 20 30] [40 50]
[20 30 40] [50 60]
[30 40 50] [60 70]
[40 50 60] [70 80]
[50 60 70] [80 90]


## Vector output model

In [173]:
# Reshape input
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [174]:
def vec_ouput_model(n_steps_in, n_steps_out, n_features):
    model = Sequential()
    model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps_in, n_features)))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Flatten())
    model.add(Dense(50, activation='relu'))
    model.add(Dense(n_steps_out))
    model.compile(optimizer='adam', loss='mse')
    
    return model

In [175]:
model = vec_ouput_model(n_steps_in, n_steps_out, n_features)
model.fit(X, y, epochs=2000 ,verbose=0)

In [176]:
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps_in, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[102.60868 114.8467 ]]


# Multiple Parallel Input and Multi-Step Output

In [177]:
def split_sequences(sequences, n_steps_in, n_steps_out):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps_in
		out_end_ix = end_ix + n_steps_out
		# check if we are beyond the dataset
		if out_end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix:out_end_ix, :]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [178]:
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# convert into input/output
X, y = split_sequences(dataset, n_steps_in, n_steps_out)
# flatten output
n_output = y.shape[1] * y.shape[2]
y = y.reshape((y.shape[0], n_output))
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]

In [179]:
def parallel_input_and_multi_step_output(n_steps_in, n_features, n_output):
    model = Sequential()
    model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps_in, n_features)))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Flatten())
    model.add(Dense(50, activation='relu'))
    model.add(Dense(n_output))
    model.compile(optimizer='adam', loss='mse')
    return model

In [182]:
model = parallel_input_and_multi_step_output(n_steps_in, n_features, n_output)
model.fit(X, y, epochs=7000, verbose=0)

## Predict

In [183]:
x_input = array([[60, 65, 125], [70, 75, 145], [80, 85, 165]])
x_input = x_input.reshape((1, n_steps_in, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[ 91.85172   96.57551  188.00807  102.45205  108.148544 210.068   ]]


# Done!